# Data Cleaning for Tableau Visualizations

In [1]:
#Importing the necessary

import pandas as pd
import numpy as np

In [2]:
#Importing raw data

data = pd.read_csv('5.csv')

C:\Users\Rhythm\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (1,12,14,28,29,30,31,32,33,36,72,73,76,78,80,81,98,99,117,124,147,170,178,185,186,193,194) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
data

,w_id,hl_id,client_w_id,state,district,rural,stratum_code,psu_id,house_no,house_hold_no,...,anym,respondentname,rtelephoneno,isnewrecord,recordupdatedcount,recordstatus,schedule_id,year,id,v204
0,NaN,NaN,NaN,5,13,1,2,100426933,4,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,3,1490121,NaN
1,NaN,NaN,NaN,5,13,1,2,100426778,8,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,3,1490122,NaN
2,NaN,NaN,NaN,5,13,1,2,100427331,11,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,3,1490123,NaN
3,NaN,NaN,NaN,5,13,1,2,100427695,20,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,3,1490124,NaN
4,NaN,NaN,NaN,5,13,1,2,100427501,21,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,3,1490125,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941126,NaN,NaN,NaN,5,2,2,0,100505198,36,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,2,9023060,NaN
941127,NaN,NaN,NaN,5,2,2,0,100505166,43,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,2,9023061,NaN
941128,NaN,NaN,NaN,5,2,2,0,100505164,44,1,...,NaN,NaN,NaN,1.0,1.0,2.0,2,2,9023062,NaN
941129,NaN,NaN,NaN,5,2,2,0,100505183,46,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,2,9023063,NaN
941130,NaN,NaN,NaN,5,2,2,0,100505140,51,1,...,NaN,NaN,NaN,NaN,1.0,2.0,2,2,9023064,NaN

In [4]:
#Taking into consideration, the data of females and that too only for the interviews which were successfully calculated

data = data[data["sex"] == 2]
data = data[data["result_of_interview"] == 1]

In [5]:
#Removing unnecessary columns

columns_to_be_removed = ['w_id', 'hl_id', 'client_w_id', 'state', 'psu_id', 'house_no', 'house_hold_no', 'year_of_intr', 
                         'month_of_intr', 'date_of_intr', 'fid', 'hh_id', 'client_hh_id', 'hh_serial_no', 'member_identity', 
                         'father_serial_no', 'mother_serial_no', 'date_of_birth', 'month_of_birth', 'date_of_marriage', 
                         'month_of_marriage', 'status', 'hh_expall_status', 'client_hl_id', 'building_no', 'hl_expall_status', 'sn', 'housestatus', 'isheadchanged', 'headname', 'fidx', 
                         'as', 'as_binned', 'fidh', 'cdoi', 'edt', 'occupation', 'catage1', 'marital', 'modern', 'traditional', 
                         'anym', 'respondentname', 'rtelephoneno', 'isnewrecord', 'recordupdatedcount', 'recordstatus', 
                         'schedule_id', 'year', 'id', 'v204', 'other_int_code', 'last_preg_no', 'previous_last_preg_no', 
                         'second_last_preg_no', 'third_last_preg_no', 'w_expall_status', 'w_status', 'twsi_id', 
                         'client_twsi_id', 'currently_widow', 'during_pregnancy', 'during_lactation', 'aware_of_haf', 
                         'twsi_expall_status', 'currently_attending_school', 'reason_for_not_attending_school', 
                         'new_born_alive_female', 'new_born_alive_male', 'new_born_alive_total', 'new_surviving_female', 
                         'new_surviving_male', 'new_surviving_total', 'isdeadmigrated', 'ever_born', 
                         'serial_no', 'identifcation_code', 'symptoms_pertaining_illness', 'sought_medical_care', 
                         'diagnosis_source', 'regular_treatment', 'regular_treatment_source', 'water_filteration', 
                         'is_toilet_shared', 'no_of_dwelling_rooms', 'current_mar_status', 'is_husband_living_with_you', 
                         'compensation_after_ster', 'received_compensation_after_ster', 'received_compensation_ster_rs', 
                         'residancial_status', 'householdstatus', 'currently_dead_or_out_migrated', 'usual_residance', 'relation_to_head', 'treatment_source', 'months_of_preg_first_anc', 'healthscheme_1', 'healthscheme_2', 'wt', 'sex', 'result_of_interview']

In [6]:
li_dif = [i for i in data.columns if i not in data.columns or i not in columns_to_be_removed]
len(li_dif)

100

In [7]:
for column in columns_to_be_removed:
    data = data.drop([column], axis=1)

In [8]:
data

,district,rural,stratum_code,age,marital_status,delivered_any_baby,born_alive_female,born_alive_male,born_alive_total,surviving_female,...,no_of_times_conceived,age_at_first_conception,is_injectable_contraceptive,health_prob_afters_fp_use,counselled_for_menstrual_hyg,aware_abt_haf,aware_abt_ort_ors,aware_abt_ort_ors_zinc,aware_abt_danger_signs_new_born,iscoveredbyhealthscheme
0,13,1,2,42,3,1.0,2.0,1.0,3.0,2.0,...,3.0,18.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,2.0
1,13,1,2,47,3,1.0,3.0,3.0,6.0,3.0,...,7.0,17.0,2.0,0.0,2.0,1.0,1.0,2.0,2.0,2.0
2,13,1,2,32,3,1.0,2.0,2.0,4.0,1.0,...,6.0,19.0,1.0,0.0,2.0,1.0,1.0,2.0,2.0,2.0
3,13,1,2,20,3,1.0,1.0,0.0,1.0,1.0,...,2.0,17.0,2.0,0.0,1.0,1.0,1.0,2.0,2.0,1.0
4,13,1,2,27,3,1.0,0.0,3.0,3.0,0.0,...,3.0,19.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941126,2,2,0,36,3,1.0,2.0,4.0,6.0,2.0,...,6.0,19.0,1.0,NaN,2.0,1.0,1.0,1.0,1.0,2.0
941127,2,2,0,39,3,1.0,2.0,1.0,3.0,2.0,...,3.0,15.0,2.0,NaN,2.0,1.0,1.0,2.0,1.0,2.0
941128,2,2,0,41,3,1.0,1.0,2.0,3.0,1.0,...,3.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
941129,2,2,0,38,3,1.0,1.0,1.0,2.0,1.0,...,2.0,22.0,2.0,NaN,2.0,1.0,1.0,2.0,1.0,2.0
941130,2,2,0,43,3,1.0,1.0,1.0,2.0,1.0,...,2.0,19.0,1.0,NaN,2.0,1.0,1.0,1.0,1.0,2.0

In [9]:
count = 0
for i in data[data.columns[13]]:
    if i == 21:
        count += 1
count

1

In [10]:
for col in data.columns:
    print(col, data[col].unique())

district [13  6  5  1  4 11  3  7 10  9  2  8 12]
rural [1 2]
stratum_code [2 1 0]
age [ 42  47  32  20  27  29  26  30  40  39  38  28  22  19  34  25  23  37
  36  33  31  43  35  41  21  44  24  46  49  45  18  48  17  16  15 548]
marital_status [ 3  4  5  6  7  2 25]
delivered_any_baby [ 1.  2. nan  8.  3.]
born_alive_female [ 2.  3.  1.  0.  4.  6.  5.  7.  8.  9. 11. 10. nan 12. 15. 32. 20. 13.
 47. 21. 54. 41. 14. 31. 30. 22. 63. 65. 61. 45.]
born_alive_male [ 1.  3.  2.  0.  6.  4.  5.  7. 10.  8.  9. 11. nan 12. 32. 14. 41. 20.
 21. 13. 22. 23. 44. 47. 45. 31.]
born_alive_total [ 3.  6.  4.  1.  5.  2.  7. 10.  0.  9.  8. 13. 11. 12. 15. 14. nan 20.
 32. 36. 23. 24. 34. 35. 16. 50. 59. 43. 45. 53. 17. 22. 21. 33. 46. 47.
 52. 63. 66. 62.]
surviving_female [ 2.  3.  1.  0.  4.  5.  6.  7.  8.  9. 10. nan 12. 11.]
surviving_male [ 0.  3.  2.  1.  4.  6.  5.  9.  7.  8. nan 20. 10.]
surviving_total [ 2.  6.  3.  1.  4.  5.  0.  8.  7. 10.  9. 12. 11. 13. nan 14. 23. 21.]
mother_age_when_baby_was_born [18. 17. 19. 20. 21. 22. 16.  0. 23. 24. 25. 27. 32. 15. 26. 28. 29. 34.
 30. 31. 14. 35. 33. 13. nan 40. 39. 36. 38. 41. 37. 42. 43. 46. 44. 45.
 47. 48.  3. 49. 12.]
outcome_pregnancy [ 2.  1. nan 21.]
is_tubectomy [ 1.  0.  2. nan]
is_vasectomy [ 1.  0.  2. nan]
is_copper_t [ 1.  0.  2. nan]
is_pills_daily [ 1.  0.  2. nan]
is_piils_weekly [ 1.  0.  2. nan]
is_emergency_contraceptive [ 1.  2.  0. nan]
is_condom [ 1.  0.  2. nan]
is_moder_methods [ 2.  0.  1. nan]
is_contraceptive [ 2.  1.  0. nan]
is_periodic_abstinence [ 1.  0.  2. nan]
is_withdrawal [ 1.  0.  2. nan]
is_amenorrahoea [ 2.  1.  0. nan]
is_other_traditional_method [ 1.  2.  0. nan]
is_currently_pregnant [ 2.  1.  0.  3. nan]
pregnant_month [ 0.  2.  6.  4.  1.  8.  7.  5.  3.  9. nan]
is_anc_registered [ 0.  1.  2. nan]
willing_to_get_pregnant [ 0.  4.  1.  2.  3. nan]
is_currently_menstruating [ 1.  0.  4.  3.  2.  6.  5. nan]
when_you_bcome_mother_last_time [ 1.  4.  0.  2.  3. nan]
is_any_fp_methos_used [ 1.  0.  2. nan]
fp_method_used [ 7.  1.  0. 14.  4.  5.  9.  6.  3. 13. 11.  8. 12. 10.  2. nan]
source_of_treatment_for_fp [ 0.  7.  1.  6.  5.  4.  2.  9.  8.  3. nan 17.]
how_long_using_this_method [ 1.  0.  2.  4.  5.  3. nan]
method_obtain_last_time [16.  0. 17.  2.  1. 14.  5.  6.  4. 11. 20.  3.  7. 15. 10.  9. 18. 13.
 19. 12.  8. nan]
reason_for_not_using_fp_method [ 0.  1. 17.  5.  3. 16.  2. 12.  7. 14.  6.  4. 10. 13. 11. 15.  9.  8.
 nan]
is_method_used_in_last_5_yrs [ 0.  1.  2. nan  5.]
method_type_used_in_last_5_yrs [ 0.  4.  5. 11.  3.  7. 12.  6.  9. 13.  8. 10. 14. nan  1.  2. 17.]
reason_for_discontinuation [ 0. 12. 18.  1.  2.  8.  4.  3. 11.  9. 13.  5. 10.  6. 17.  7. 15. 16.
 14. nan]
intend_to_use_fp_method_in_futur [ 0.  1.  2. nan 20.  3.]
when_method_is_going_to_use [ 0.  1.  4.  3.  2. nan 12.]
which_method_going_to_pefer_for_ [ 0.  4.  1.  5.  8.  7.  3.  2. 11. 12.  9. 14.  6. 10. 13. nan]
want_more_childern [ 0.  3.  1.  2. nan]
next_child_preference [ 0.  2.  3.  1. nan  5.]
time_for_next_child [ 0.  2.  1.  5.  3.  4. nan]
anm_in_last_3_months [ 0.  1.  2. nan]
aware_abt_rti [ 1.  0.  2. nan]
aware_abt_hiv [ 1.  0.  2. nan]
aware_of_the_danger_signs [ 1.  0.  2. nan -1.]
year_of_birth [1969. 1964. 1979. 1991. 1984. 1982. 1985. 1981. 1971. 1972. 1973. 1983.
 1989. 1992. 1977. 1986. 1988. 1974. 1975. 1978. 1980. 1968. 1976. 1970.
 1990. 1967. 1987. 1965. 1962. 1966. 1993. 1963. 1994. 1995. 1996. 2011.
 1946. 1999. 1959. 1957. 1961. 1998.    0. 1960. 1920. 1997. 1951. 1950.
 1956. 1944. 1919. 1934.]
religion [1.000e+00 2.000e+00 3.000e+00 7.000e+00 4.000e+00 6.000e+00 5.000e+00
 1.985e+03]
social_group_code [3. 1. 2.]
year_of_marriage [1983. 1985. 1997. 2009. 2005. 1999. 2004. 1995. 1986. 1979. 1992. 1993.
 1994. 2001. 2010. 2011. 1974. 2007. 1989. 2002. 1996. 2006. 1987. 2000.
 2008. 1988. 1990. 1984. 2003. 1982. 1975. 1980. 1991. 1981. 1998. 1976.
 1978. 1970. 1977. 1968. 1972. 1971. 1973. 1963. 1966. 1969. 1964. 1967.
    0. 1965.   10.  991.  198. 1962. 1958.  984. 1961. 1959. 1957. 1948.
 1950. 1945.   nan 1952. 1955. 1960. 1947. 1940.]
highest_qualification [ 0.  3.  5.  6.  4.  1.  8.  7.  2.  9. nan]
occupation_status [10.  6.  3.  4.  7. 13. 11.  1. 16. 14.  5.  2.  9.  8. 15. 12. nan  0.]
disability_status [ 0.  7.  5.  1.  4.  2.  6.  3. nan 10.]
injury_treatment_type [ 0.  6.  2.  3.  7.  5.  4.  1. nan]
illness_type [ 0.  5.  6.  7.  3.  4.  1.  9.  2.  8. nan]
diagnosed_for [ 0. 99.  2.  7.  5. 10. 17. 31.  1. 19. 30. 18. 15.  9. 20.  4. 21. 16.
  3. 14. 25.  6. 27. 12. 11.  8. 13. 22. nan 23. 29. 24. 28. 26.]
chew [ 7.  1.  3.  0. nan  2.  5.  4.  6.]
smoke [ 4.  1.  0. nan  3.  2.]
alcohol [ 4.  2.  0. nan  1.  3.]
house_status [ 1. nan  3.  2.  4.  0.]
house_structure [ 3. nan  1.  2.  4.]
owner_status [ 3.  1.  2. nan  0.]
drinking_water_source [ 1.  3.  2. nan  9.  4.  8.  6.  5.  7.]
is_water_filter [ 2. nan  1.]
toilet_used [ 3.  0. nan  7.  2.  1.  4.  6.  8.  9.  5.]
household_have_electricity [ 1.  2. nan]
lighting_source [ 1.  2. nan  3.  6.  5.  4.]
cooking_fuel [ 6.  1. nan  2.  3.  0.  4.  5.  7.  8.  9.]
kitchen_availability [ 2.  4.  3. nan  1.  5.]
is_radio [ 1.  2. nan]
is_television [ 1.  2. nan]
is_computer [ 3. nan  2.  1.]
is_telephone [ 2. nan  3.  4.  1.]
is_washing_machine [ 2. nan  1.]
is_refrigerator [ 1.  2. nan]
is_sewing_machine [ 1.  2. nan]
is_bicycle [ 2.  1. nan]
is_scooter [ 1.  2. nan]
is_car [ 2. nan  1.]
is_tractor [ 2. nan  1.]
is_water_pump [ 2. nan  1.]
cart [ 4. nan  1.  2.  3.]
land_possessed [ 6. nan  1.  2.  4.  3.  5.]
ever_conceived [ 1.  2.  0. nan]
no_of_times_conceived [ 3.  7.  6.  2.  1.  4. 10.  5.  8.  9.  0. 12. 13. 11. 15. 14. nan]
age_at_first_conception [18. 17. 19. 20. 21. 22. 16. 23. 24. 25.  0. 27. 32. 15. 26. 29. 31. 28.
 33. 35. 30. 13. 14. 34. 12. nan 36. 40. 38. 37. 41. 39. 42. 45. 43. 44.
 46. 47. 48.  3.]
is_injectable_contraceptive [ 2.  1.  0. nan]
health_prob_afters_fp_use [ 2.  0.  1. nan  4.  3.  5.]
counselled_for_menstrual_hyg [ 2.  1.  0. nan]
aware_abt_haf [ 1.  0.  2. nan  3.]
aware_abt_ort_ors [ 1.  0.  2. nan  3.]
aware_abt_ort_ors_zinc [ 2.  0.  1. nan]
aware_abt_danger_signs_new_born [ 2.  1.  0. nan]
iscoveredbyhealthscheme [ 2.  1.  3. nan  0.]

In [11]:
print(data.columns[13])
data[data.columns[13]].unique()

outcome_pregnancy

array([ 2.,  1., nan, 21.])

In [12]:
l = [13, '52(sex)']
tobeaddedagain = ['is_washing_machine', 'is_refrigerator', 'is_sewing_machine', 'is_bicycle', 'is_scooter', 'is_car', 'is_tractor', 'is_water_pump', 'cart']

In [27]:
#Replacing the NaN values with suitable inputs



data["next_child_preference"] = data["next_child_preference"].replace([' ', 0, '0', 5, '5'], -1).fillna(-1).astype(int)

data[["marital_status", "chew"]] = data[["marital_status", "chew"]].replace([' ', 25], 8).fillna(8).astype(int)

data["delivered_any_baby"] = data["delivered_any_baby"].replace([' ', 8, 3], -1).fillna(-1).astype(int)

data[["born_alive_female", "born_alive_male", "born_alive_total", "surviving_female", "surviving_male", "surviving_total", "no_of_times_conceived"]] = data[["born_alive_female", "born_alive_male", "born_alive_total", "surviving_female", "surviving_male", "surviving_total", "no_of_times_conceived"]].replace([' '], -1).fillna(-1).astype(int)

data[["mother_age_when_baby_was_born", "how_long_using_this_method", "method_obtain_last_time"]] = data[["mother_age_when_baby_was_born", "how_long_using_this_method", "method_obtain_last_time"]].replace([' ', 0, '0'], -1).fillna(-1).astype(int)

data[["is_tubectomy", "is_vasectomy", "is_copper_t", "is_pills_daily", "is_piils_weekly", "is_emergency_contraceptive", "is_condom", "is_moder_methods", "is_contraceptive", "is_periodic_abstinence", "is_withdrawal", "is_amenorrahoea", "is_other_traditional_method", "house_status", "is_injectable_contraceptive"]] = data[["is_tubectomy", "is_vasectomy", "is_copper_t", "is_pills_daily", "is_piils_weekly", "is_emergency_contraceptive", "is_condom", "is_moder_methods", "is_contraceptive", "is_periodic_abstinence", "is_withdrawal", "is_amenorrahoea", "is_other_traditional_method", "house_status", "is_injectable_contraceptive"]].replace([' ', 0], -1).fillna(-1).astype(int)

data[["is_currently_pregnant", "pregnant_month", "is_anc_registered", "willing_to_get_pregnant", "when_you_bcome_mother_last_time", "reason_for_not_using_fp_method", "reason_for_discontinuation", "want_more_childern", "time_for_next_child"]] = data[["is_currently_pregnant", "pregnant_month", "is_anc_registered", "willing_to_get_pregnant", "when_you_bcome_mother_last_time", "reason_for_not_using_fp_method", "reason_for_discontinuation", "want_more_childern", "time_for_next_child"]].replace([' ', 0, '0'], -1).fillna(-1).astype(int)

data["is_currently_menstruating"] = data["is_currently_menstruating"].replace([' ', 0], 7).fillna(7).astype(int)

data["is_any_fp_methos_used"] = data["is_any_fp_methos_used"].replace([' ', 0, '0'], 3).fillna(3).astype(int)

data["fp_method_used"] = data["fp_method_used"].replace([' ', 0, '0', 14, '14'], -1).fillna(-1).astype(int)

data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace([' ', 0, '0', 17], -1).fillna(-1).astype(int)

data["is_method_used_in_last_5_yrs"] = data["is_method_used_in_last_5_yrs"].replace([' ', 0, '0', 5], -1).fillna(-1).astype(int)

data[["method_type_used_in_last_5_yrs", "which_method_going_to_pefer_for_"]] = data[["method_type_used_in_last_5_yrs", "which_method_going_to_pefer_for_"]].replace([' ', 0, '0', 14, '14', '17'], -1).fillna(-1).astype(int)

data["intend_to_use_fp_method_in_futur"] = data["intend_to_use_fp_method_in_futur"].replace([' ', 0, '0', '3', 20, '17'], -1).fillna(-1).astype(int)

data["when_method_is_going_to_use"] = data["when_method_is_going_to_use"].replace([' ', 0, '0', 12], -1).fillna(-1).astype(int)

data["anm_in_last_3_months"] = data["anm_in_last_3_months"].replace([' ', 0, '0', '8'], 3).fillna(3).astype(int)

data[["aware_abt_rti", "aware_abt_hiv", "aware_of_the_danger_signs"]] = data[["aware_abt_rti", "aware_abt_hiv", "aware_of_the_danger_signs"]].replace([' ', 0, '0', '-1'], 2).fillna(2).astype(int)

data[["year_of_birth", "religion", "social_group_code"]] = data[["year_of_birth", "religion", "social_group_code"]].replace([2011, 1985], 0).fillna(0).astype(int)

data["year_of_marriage"] = data["year_of_marriage"].replace([10, 991, 198, 984], 0).fillna(0).astype(int)

data[["highest_qualification", "injury_treatment_type", "illness_type", "diagnosed_for"]] = data[["highest_qualification", "injury_treatment_type", "illness_type", "diagnosed_for"]].fillna(-1).astype(int)

data["occupation_status"] = data["occupation_status"].replace([0], -1).fillna(-1).astype(int)

data["disability_status"] = data["disability_status"].replace([10], -1).fillna(-1).astype(int)

data[["smoke", "alcohol"]] = data[["smoke", "alcohol"]].replace([' '], 5).fillna(5).astype(int)

data["house_structure"] = data["house_structure"].replace([' ', 'SIKANDER'], 4).fillna(4).astype(int)

data["owner_status"] = data["owner_status"].replace([' '], 3).fillna(3).astype(int)
data["owner_status"] = data["owner_status"].replace([0], 3).fillna(3).astype(int)

data[["drinking_water_source", "cooking_fuel"]] = data[["drinking_water_source", "cooking_fuel"]].replace([' '], 9).fillna(9).astype(int)

data[["is_water_filter", "household_have_electricity", "is_radio", "is_television"]] = data[["is_water_filter", "household_have_electricity", "is_radio", "is_television"]].replace([' '], 2).fillna(2).astype(int)

data["toilet_used"] = data["toilet_used"].replace([' '], 0).fillna(0).astype(int)

data["lighting_source"] = data["lighting_source"].replace([' '], 6).fillna(6).astype(int)

data["kitchen_availability"] = data["kitchen_availability"].replace([' '], 2).fillna(2).astype(int)

data["is_computer"] = data["is_computer"].replace([' '], 3).fillna(3).astype(int)

data["is_telephone"] = data["is_telephone"].replace([' '], 4).fillna(4).astype(int)

data["land_possessed"] = data["land_possessed"].replace([' '], 6).fillna(6).astype(int)

data["ever_conceived"] = data["ever_conceived"].replace([' ', 0, 'W05UT_052016200590502'], 2).fillna(2).astype(int)

data["age_at_first_conception"] = data["age_at_first_conception"].replace([' ', 0, 1, 3], -1).fillna(-1).astype(int)

data["health_prob_afters_fp_use"] = data["health_prob_afters_fp_use"].replace([' ', 0, '0', 3, '3', 4, '4', 5, '5'], -1).fillna(-1).astype(int)

data["counselled_for_menstrual_hyg"] = data["counselled_for_menstrual_hyg"].replace([' ', 0], 2).fillna(2).astype(int)

data[["aware_abt_haf", "aware_abt_ort_ors", "aware_abt_ort_ors_zinc", "aware_abt_danger_signs_new_born"]] = data[["aware_abt_haf", "aware_abt_ort_ors", "aware_abt_ort_ors_zinc", "aware_abt_danger_signs_new_born"]].replace([' ', 0, 3], 2).fillna(2).astype(int)

data["iscoveredbyhealthscheme"] = data["iscoveredbyhealthscheme"].replace([0], 3).fillna(3).astype(int)

data[["is_washing_machine", "is_refrigerator", "is_sewing_machine", "is_bicycle", "is_scooter", "is_car", "is_tractor", "is_water_pump"]] = data[["is_washing_machine", "is_refrigerator", "is_sewing_machine", "is_bicycle", "is_scooter", "is_car", "is_tractor", "is_water_pump"]].replace([' '], 2).fillna(2).astype(int)

data["cart"] = data["cart"].replace([' '], 4).fillna(4).astype(int)

In [54]:
data.to_csv('clean5.csv')

In [55]:
data

,district,rural,stratum_code,age,marital_status,delivered_any_baby,born_alive_female,born_alive_male,born_alive_total,surviving_female,...,no_of_times_conceived,age_at_first_conception,is_injectable_contraceptive,health_prob_afters_fp_use,counselled_for_menstrual_hyg,aware_abt_haf,aware_abt_ort_ors,aware_abt_ort_ors_zinc,aware_abt_danger_signs_new_born,iscoveredbyhealthscheme
0,13,1,2,42,3,1,2,1,3,2,...,3,18,2,2,2,1,1,2,2,2
1,13,1,2,47,3,1,3,3,6,3,...,7,17,2,-1,2,1,1,2,2,2
2,13,1,2,32,3,1,2,2,4,1,...,6,19,1,-1,2,1,1,2,2,2
3,13,1,2,20,3,1,1,0,1,1,...,2,17,2,-1,1,1,1,2,2,1
4,13,1,2,27,3,1,0,3,3,0,...,3,19,1,2,1,1,1,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
941126,2,2,0,36,3,1,2,4,6,2,...,6,19,1,-1,2,1,1,1,1,2
941127,2,2,0,39,3,1,2,1,3,2,...,3,15,2,-1,2,1,1,2,1,2
941128,2,2,0,41,3,1,1,2,3,1,...,3,22,-1,-1,2,2,2,2,2,2
941129,2,2,0,38,3,1,1,1,2,1,...,2,22,2,-1,2,1,1,2,1,2
941130,2,2,0,43,3,1,1,1,2,1,...,2,19,1,-1,2,1,1,1,1,2

In [56]:
alpha = data.dtypes

In [57]:
alpha

district                           int64
rural                              int64
stratum_code                       int64
age                                int64
marital_status                     int32
                                   ...
aware_abt_haf                      int32
aware_abt_ort_ors                  int32
aware_abt_ort_ors_zinc             int32
aware_abt_danger_signs_new_born    int32
iscoveredbyhealthscheme            int32
Length: 100, dtype: object

In [58]:
data = data.reset_index(drop=True)
data

,district,rural,stratum_code,age,marital_status,delivered_any_baby,born_alive_female,born_alive_male,born_alive_total,surviving_female,...,no_of_times_conceived,age_at_first_conception,is_injectable_contraceptive,health_prob_afters_fp_use,counselled_for_menstrual_hyg,aware_abt_haf,aware_abt_ort_ors,aware_abt_ort_ors_zinc,aware_abt_danger_signs_new_born,iscoveredbyhealthscheme
0,13,1,2,42,3,1,2,1,3,2,...,3,18,2,2,2,1,1,2,2,2
1,13,1,2,47,3,1,3,3,6,3,...,7,17,2,-1,2,1,1,2,2,2
2,13,1,2,32,3,1,2,2,4,1,...,6,19,1,-1,2,1,1,2,2,2
3,13,1,2,20,3,1,1,0,1,1,...,2,17,2,-1,1,1,1,2,2,1
4,13,1,2,27,3,1,0,3,3,0,...,3,19,1,2,1,1,1,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905972,2,2,0,36,3,1,2,4,6,2,...,6,19,1,-1,2,1,1,1,1,2
905973,2,2,0,39,3,1,2,1,3,2,...,3,15,2,-1,2,1,1,2,1,2
905974,2,2,0,41,3,1,1,2,3,1,...,3,22,-1,-1,2,2,2,2,2,2
905975,2,2,0,38,3,1,1,1,2,1,...,2,22,2,-1,2,1,1,2,1,2
905976,2,2,0,43,3,1,1,1,2,1,...,2,19,1,-1,2,1,1,1,1,2

In [59]:
#Since the numbers in most of the columns depict category and not numerical value, hence changing them to string format

data['district'] = data['district'].apply(str)
data['rural'] = data['rural'].apply(str)
data['stratum_code'] = data['stratum_code'].apply(str)
data['marital_status'] = data['marital_status'].apply(str)
data['delivered_any_baby'] = data['delivered_any_baby'].apply(str)
data['outcome_pregnancy'] = data['outcome_pregnancy'].apply(str)
data['is_tubectomy'] = data['is_tubectomy'].apply(str)
data['is_vasectomy'] = data['is_vasectomy'].apply(str)
data['is_copper_t'] = data['is_copper_t'].apply(str)
data['is_pills_daily'] = data['is_pills_daily'].apply(str)
data['is_piils_weekly'] = data['is_piils_weekly'].apply(str)
data['is_emergency_contraceptive'] = data['is_emergency_contraceptive'].apply(str)
data['is_condom'] = data['is_condom'].apply(str)
data['is_moder_methods'] = data['is_moder_methods'].apply(str)
data['is_contraceptive'] = data['is_contraceptive'].apply(str)
data['is_periodic_abstinence'] = data['is_periodic_abstinence'].apply(str)
data['is_withdrawal'] = data['is_withdrawal'].apply(str)
data['is_amenorrahoea'] = data['is_amenorrahoea'].apply(str)
data['is_other_traditional_method'] = data['is_other_traditional_method'].apply(str)
data['is_currently_pregnant'] = data['is_currently_pregnant'].apply(str)
data['is_anc_registered'] = data['is_anc_registered'].apply(str)
data['willing_to_get_pregnant'] = data['willing_to_get_pregnant'].apply(str)
data['is_currently_menstruating'] = data['is_currently_menstruating'].apply(str)
data['when_you_bcome_mother_last_time'] = data['when_you_bcome_mother_last_time'].apply(str)
data['is_any_fp_methos_used'] = data['is_any_fp_methos_used'].apply(str)
data['fp_method_used'] = data['fp_method_used'].apply(str)
data['source_of_treatment_for_fp'] = data['source_of_treatment_for_fp'].apply(str)
data['how_long_using_this_method'] = data['how_long_using_this_method'].apply(str)
data['method_obtain_last_time'] = data['method_obtain_last_time'].apply(str)
data['reason_for_not_using_fp_method'] = data['reason_for_not_using_fp_method'].apply(str)
data['is_method_used_in_last_5_yrs'] = data['is_method_used_in_last_5_yrs'].apply(str)
data['method_type_used_in_last_5_yrs'] = data['method_type_used_in_last_5_yrs'].apply(str)
data['reason_for_discontinuation'] = data['reason_for_discontinuation'].apply(str)
data['when_method_is_going_to_use'] = data['when_method_is_going_to_use'].apply(str)
data['want_more_childern'] = data['want_more_childern'].apply(str)
data['next_child_preference'] = data['next_child_preference'].apply(str)
data['time_for_next_child'] = data['time_for_next_child'].apply(str)
data['anm_in_last_3_months'] = data['anm_in_last_3_months'].apply(str)
data['aware_abt_rti'] = data['aware_abt_rti'].apply(str)
data['aware_abt_hiv'] = data['aware_abt_hiv'].apply(str)
data['aware_of_the_danger_signs'] = data['aware_of_the_danger_signs'].apply(str)
data['religion'] = data['religion'].apply(str)
data['social_group_code'] = data['social_group_code'].apply(str)
data['highest_qualification'] = data['highest_qualification'].apply(str)
data['occupation_status'] = data['occupation_status'].apply(str)
data['disability_status'] = data['disability_status'].apply(str)
data['injury_treatment_type'] = data['injury_treatment_type'].apply(str)
data['illness_type'] = data['illness_type'].apply(str)
data['diagnosed_for'] = data['diagnosed_for'].apply(str)
data['chew'] = data['chew'].apply(str)
data['smoke'] = data['smoke'].apply(str)
data['alcohol'] = data['alcohol'].apply(str)
data['house_status'] = data['house_status'].apply(str)
data['house_structure'] = data['house_structure'].apply(str)
data['owner_status'] = data['owner_status'].apply(str)
data['drinking_water_source'] = data['drinking_water_source'].apply(str)
data['is_water_filter'] = data['is_water_filter'].apply(str)
data['toilet_used'] = data['toilet_used'].apply(str)
data['household_have_electricity'] = data['household_have_electricity'].apply(str)
data['lighting_source'] = data['lighting_source'].apply(str)
data['cooking_fuel'] = data['cooking_fuel'].apply(str)
data['kitchen_availability'] = data['kitchen_availability'].apply(str)
data['is_radio'] = data['is_radio'].apply(str)
data['is_television'] = data['is_television'].apply(str)
data['is_computer'] = data['is_computer'].apply(str)
data['is_telephone'] = data['is_telephone'].apply(str)
data['is_washing_machine'] = data['is_washing_machine'].apply(str)
data['is_refrigerator'] = data['is_refrigerator'].apply(str)
data['is_sewing_machine'] = data['is_sewing_machine'].apply(str)
data['is_bicycle'] = data['is_bicycle'].apply(str)
data['is_scooter'] = data['is_scooter'].apply(str)
data['is_car'] = data['is_car'].apply(str)
data['is_tractor'] = data['is_tractor'].apply(str)
data['is_water_pump'] = data['is_water_pump'].apply(str)
data['cart'] = data['cart'].apply(str)
data['land_possessed'] = data['land_possessed'].apply(str)
data['ever_conceived'] = data['ever_conceived'].apply(str)
data['is_injectable_contraceptive'] = data['is_injectable_contraceptive'].apply(str)
data['health_prob_afters_fp_use'] = data['health_prob_afters_fp_use'].apply(str)
data['counselled_for_menstrual_hyg'] = data['counselled_for_menstrual_hyg'].apply(str)
data['aware_abt_haf'] = data['aware_abt_haf'].apply(str)
data['aware_abt_ort_ors'] = data['aware_abt_ort_ors'].apply(str)
data['aware_abt_ort_ors_zinc'] = data['aware_abt_ort_ors_zinc'].apply(str)
data['aware_abt_danger_signs_new_born'] = data['aware_abt_danger_signs_new_born'].apply(str)
data['iscoveredbyhealthscheme'] = data['iscoveredbyhealthscheme'].apply(str)
data['intend_to_use_fp_method_in_futur'] = data['intend_to_use_fp_method_in_futur'].apply(str)
data['which_method_going_to_pefer_for_'] = data['which_method_going_to_pefer_for_'].apply(str)

In [60]:
beta = data.dtypes
beta

district                           object
rural                              object
stratum_code                       object
age                                 int64
marital_status                     object
                                    ...
aware_abt_haf                      object
aware_abt_ort_ors                  object
aware_abt_ort_ors_zinc             object
aware_abt_danger_signs_new_born    object
iscoveredbyhealthscheme            object
Length: 100, dtype: object

In [61]:
data

,district,rural,stratum_code,age,marital_status,delivered_any_baby,born_alive_female,born_alive_male,born_alive_total,surviving_female,...,no_of_times_conceived,age_at_first_conception,is_injectable_contraceptive,health_prob_afters_fp_use,counselled_for_menstrual_hyg,aware_abt_haf,aware_abt_ort_ors,aware_abt_ort_ors_zinc,aware_abt_danger_signs_new_born,iscoveredbyhealthscheme
0,13,1,2,42,3,1,2,1,3,2,...,3,18,2,2,2,1,1,2,2,2
1,13,1,2,47,3,1,3,3,6,3,...,7,17,2,-1,2,1,1,2,2,2
2,13,1,2,32,3,1,2,2,4,1,...,6,19,1,-1,2,1,1,2,2,2
3,13,1,2,20,3,1,1,0,1,1,...,2,17,2,-1,1,1,1,2,2,1
4,13,1,2,27,3,1,0,3,3,0,...,3,19,1,2,1,1,1,2,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905972,2,2,0,36,3,1,2,4,6,2,...,6,19,1,-1,2,1,1,1,1,2
905973,2,2,0,39,3,1,2,1,3,2,...,3,15,2,-1,2,1,1,2,1,2
905974,2,2,0,41,3,1,1,2,3,1,...,3,22,-1,-1,2,2,2,2,2,2
905975,2,2,0,38,3,1,1,1,2,1,...,2,22,2,-1,2,1,1,2,1,2
905976,2,2,0,43,3,1,1,1,2,1,...,2,19,1,-1,2,1,1,1,1,2

## From here onwards, all the numbers are replaced with their actual string names

In [62]:
data["district"] = data["district"].replace(['1'], 'Uttarkashi')
data["district"] = data["district"].replace(['2'], 'Chamoli')
data["district"] = data["district"].replace(['3'], 'Rudraprayag')
data["district"] = data["district"].replace(['4'], 'Tehri Garhwal')
data["district"] = data["district"].replace(['5'], 'Dehradun')
data["district"] = data["district"].replace(['6'], 'Garhwal')
data["district"] = data["district"].replace(['7'], 'Pithoragarh')
data["district"] = data["district"].replace(['8'], 'Bageshwar')
data["district"] = data["district"].replace(['9'], 'Almora')
data["district"] = data["district"].replace(['10'], 'Champawat')
data["district"] = data["district"].replace(['11'], 'Nainital')
data["district"] = data["district"].replace(['12'], 'Udham Singh Nagar')
data["district"] = data["district"].replace(['13'], 'Hardwar')

In [65]:
data["rural"] = data["rural"].replace(['1'], 'Rural')
data["rural"] = data["rural"].replace(['2'], 'Urban')

In [67]:
data["marital_status"] = data["marital_status"].replace(['2'], 'Married but Gauna not performed')
data["marital_status"] = data["marital_status"].replace(['3'], 'Married and Gauna performed')
data["marital_status"] = data["marital_status"].replace(['4'], 'Remarried')
data["marital_status"] = data["marital_status"].replace(['5'], 'Widow/Widower')
data["marital_status"] = data["marital_status"].replace(['6'], 'Divorced')
data["marital_status"] = data["marital_status"].replace(['7'], 'Separated')
data["marital_status"] = data["marital_status"].replace(['8'], 'Not stated')

In [68]:
data["delivered_any_baby"] = data["delivered_any_baby"].replace(['1'], 'Yes')
data["delivered_any_baby"] = data["delivered_any_baby"].replace(['2'], 'No')
data["delivered_any_baby"] = data["delivered_any_baby"].replace(['3'], 'Not stated')

In [70]:
data["is_tubectomy"] = data["is_tubectomy"].replace(['1'], 'Yes')
data["is_tubectomy"] = data["is_tubectomy"].replace(['2'], 'No')
data["is_tubectomy"] = data["is_tubectomy"].replace(['3'], 'Not aware')
data["is_tubectomy"] = data["is_tubectomy"].replace(['-1'], 'Not applicable')

In [71]:
data["is_vasectomy"] = data["is_vasectomy"].replace(['1'], 'Yes')
data["is_vasectomy"] = data["is_vasectomy"].replace(['2'], 'No')
data["is_vasectomy"] = data["is_vasectomy"].replace(['3'], 'Not aware')
data["is_vasectomy"] = data["is_vasectomy"].replace(['-1'], 'Not applicable')

In [72]:
data["is_copper_t"] = data["is_copper_t"].replace(['1'], 'Yes')
data["is_copper_t"] = data["is_copper_t"].replace(['2'], 'No')
data["is_copper_t"] = data["is_copper_t"].replace(['3'], 'Not aware')
data["is_copper_t"] = data["is_copper_t"].replace(['-1'], 'Not applicable')

In [73]:
data["is_pills_daily"] = data["is_pills_daily"].replace(['1'], 'Yes')
data["is_pills_daily"] = data["is_pills_daily"].replace(['2'], 'No')
data["is_pills_daily"] = data["is_pills_daily"].replace(['3'], 'Not aware')
data["is_pills_daily"] = data["is_pills_daily"].replace(['-1'], 'Not applicable')

In [74]:
data["is_piils_weekly"] = data["is_piils_weekly"].replace(['1'], 'Yes')
data["is_piils_weekly"] = data["is_piils_weekly"].replace(['2'], 'No')
data["is_piils_weekly"] = data["is_piils_weekly"].replace(['3'], 'Not aware')
data["is_piils_weekly"] = data["is_piils_weekly"].replace(['-1'], 'Not applicable')

In [75]:
data["is_emergency_contraceptive"] = data["is_emergency_contraceptive"].replace(['1'], 'Yes')
data["is_emergency_contraceptive"] = data["is_emergency_contraceptive"].replace(['2'], 'No')
data["is_emergency_contraceptive"] = data["is_emergency_contraceptive"].replace(['3'], 'Not aware')
data["is_emergency_contraceptive"] = data["is_emergency_contraceptive"].replace(['-1'], 'Not applicable')

In [76]:
data["is_condom"] = data["is_condom"].replace(['1'], 'Yes')
data["is_condom"] = data["is_condom"].replace(['2'], 'No')
data["is_condom"] = data["is_condom"].replace(['3'], 'Not aware')
data["is_condom"] = data["is_condom"].replace(['-1'], 'Not applicable')

In [77]:
data["is_moder_methods"] = data["is_moder_methods"].replace(['1'], 'Yes')
data["is_moder_methods"] = data["is_moder_methods"].replace(['2'], 'No')
data["is_moder_methods"] = data["is_moder_methods"].replace(['3'], 'Not aware')
data["is_moder_methods"] = data["is_moder_methods"].replace(['-1'], 'Not applicable')

In [78]:
data["is_contraceptive"] = data["is_contraceptive"].replace(['1'], 'Yes')
data["is_contraceptive"] = data["is_contraceptive"].replace(['2'], 'No')
data["is_contraceptive"] = data["is_contraceptive"].replace(['3'], 'Not aware')
data["is_contraceptive"] = data["is_contraceptive"].replace(['-1'], 'Not applicable')

In [79]:
data["is_periodic_abstinence"] = data["is_periodic_abstinence"].replace(['1'], 'Yes')
data["is_periodic_abstinence"] = data["is_periodic_abstinence"].replace(['2'], 'No')
data["is_periodic_abstinence"] = data["is_periodic_abstinence"].replace(['3'], 'Not aware')
data["is_periodic_abstinence"] = data["is_periodic_abstinence"].replace(['-1'], 'Not applicable')

In [80]:
data["is_withdrawal"] = data["is_withdrawal"].replace(['1'], 'Yes')
data["is_withdrawal"] = data["is_withdrawal"].replace(['2'], 'No')
data["is_withdrawal"] = data["is_withdrawal"].replace(['3'], 'Not aware')
data["is_withdrawal"] = data["is_withdrawal"].replace(['-1'], 'Not applicable')

In [81]:
data["is_amenorrahoea"] = data["is_amenorrahoea"].replace(['1'], 'Yes')
data["is_amenorrahoea"] = data["is_amenorrahoea"].replace(['2'], 'No')
data["is_amenorrahoea"] = data["is_amenorrahoea"].replace(['3'], 'Not aware')
data["is_amenorrahoea"] = data["is_amenorrahoea"].replace(['-1'], 'Not applicable')

In [82]:
data["is_other_traditional_method"] = data["is_other_traditional_method"].replace(['1'], 'Yes')
data["is_other_traditional_method"] = data["is_other_traditional_method"].replace(['2'], 'No')
data["is_other_traditional_method"] = data["is_other_traditional_method"].replace(['3'], 'Not aware')
data["is_other_traditional_method"] = data["is_other_traditional_method"].replace(['-1'], 'Not applicable')

In [83]:
data["is_currently_pregnant"] = data["is_currently_pregnant"].replace(['1'], 'Yes')
data["is_currently_pregnant"] = data["is_currently_pregnant"].replace(['2'], 'No')
data["is_currently_pregnant"] = data["is_currently_pregnant"].replace(['3'], 'Not sure')
data["is_currently_pregnant"] = data["is_currently_pregnant"].replace(['-1'], 'Not applicable')

In [84]:
data["is_anc_registered"] = data["is_anc_registered"].replace(['1'], 'Yes')
data["is_anc_registered"] = data["is_anc_registered"].replace(['2'], 'No')
data["is_anc_registered"] = data["is_anc_registered"].replace(['-1'], 'Not applicable')

In [85]:
data["willing_to_get_pregnant"] = data["willing_to_get_pregnant"].replace(['1'], 'Now')
data["willing_to_get_pregnant"] = data["willing_to_get_pregnant"].replace(['2'], 'Later within 2 years')
data["willing_to_get_pregnant"] = data["willing_to_get_pregnant"].replace(['3'], 'After 2 years or more')
data["willing_to_get_pregnant"] = data["willing_to_get_pregnant"].replace(['4'], 'Do not want any more children')
data["willing_to_get_pregnant"] = data["willing_to_get_pregnant"].replace(['-1'], 'Not apllicable')

In [86]:
data["is_currently_menstruating"] = data["is_currently_menstruating"].replace(['1'], 'Yes')
data["is_currently_menstruating"] = data["is_currently_menstruating"].replace(['2'], 'No-lactational amenorrhea')
data["is_currently_menstruating"] = data["is_currently_menstruating"].replace(['3'], 'No-secondary amenorrhea')
data["is_currently_menstruating"] = data["is_currently_menstruating"].replace(['4'], 'No-in menopause')
data["is_currently_menstruating"] = data["is_currently_menstruating"].replace(['5'], 'No-uterus removed')
data["is_currently_menstruating"] = data["is_currently_menstruating"].replace(['6'], 'No-never menstruated')
data["is_currently_menstruating"] = data["is_currently_menstruating"].replace(['7'], 'Not stated')

In [87]:
data["when_you_bcome_mother_last_time"] = data["when_you_bcome_mother_last_time"].replace(['1'], 'Then')
data["when_you_bcome_mother_last_time"] = data["when_you_bcome_mother_last_time"].replace(['2'], 'Later-within 2 years')
data["when_you_bcome_mother_last_time"] = data["when_you_bcome_mother_last_time"].replace(['3'], 'Later-2 years or more')
data["when_you_bcome_mother_last_time"] = data["when_you_bcome_mother_last_time"].replace(['4'], 'Did not want any(more) children')
data["when_you_bcome_mother_last_time"] = data["when_you_bcome_mother_last_time"].replace(['-1'], 'Not applicable')

In [88]:
data["is_any_fp_methos_used"] = data["is_any_fp_methos_used"].replace(['1'], 'Yes')
data["is_any_fp_methos_used"] = data["is_any_fp_methos_used"].replace(['2'], 'No')
data["is_any_fp_methos_used"] = data["is_any_fp_methos_used"].replace(['3'], 'Not aware')
data["is_any_fp_methos_used"] = data["is_any_fp_methos_used"].replace(['-1'], 'Not aware')

In [89]:
data["fp_method_used"] = data["fp_method_used"].replace(['1'], 'Tubectomy')
data["fp_method_used"] = data["fp_method_used"].replace(['2'], 'Vasectomy')
data["fp_method_used"] = data["fp_method_used"].replace(['3'], 'Copper-t/IUD')
data["fp_method_used"] = data["fp_method_used"].replace(['4'], 'Pills-daily')
data["fp_method_used"] = data["fp_method_used"].replace(['5'], 'Pills-weekly')
data["fp_method_used"] = data["fp_method_used"].replace(['6'], 'Emergency contraceptive pill')
data["fp_method_used"] = data["fp_method_used"].replace(['7'], 'Condom')
data["fp_method_used"] = data["fp_method_used"].replace(['8'], 'Other modern method')
data["fp_method_used"] = data["fp_method_used"].replace(['9'], 'Contraceptive herbs')
data["fp_method_used"] = data["fp_method_used"].replace(['10'], 'Rhythm/periodic abstinence')
data["fp_method_used"] = data["fp_method_used"].replace(['11'], 'Withdrawl')
data["fp_method_used"] = data["fp_method_used"].replace(['12'], 'Lactational amenorrhoea method')
data["fp_method_used"] = data["fp_method_used"].replace(['13'], 'Other traditional method')
data["fp_method_used"] = data["fp_method_used"].replace(['-1'], 'Not applicable')

In [90]:
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['1'], 'Government/Municipal hospital')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['2'], 'Government dispensary')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['3'], 'Government UHC/UHP/UFWC')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['4'], 'Government CHC')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['5'], 'Government PHC')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['6'], 'Government Camp')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['7'], 'Private hospital')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['8'], 'Private dispensary/clinic')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['9'], 'Other')
data["source_of_treatment_for_fp"] = data["source_of_treatment_for_fp"].replace(['-1'], 'Not applicable')

In [91]:
data["how_long_using_this_method"] = data["how_long_using_this_method"].replace(['1'], 'Less than 6 months')
data["how_long_using_this_method"] = data["how_long_using_this_method"].replace(['2'], '6 months to <1 year')
data["how_long_using_this_method"] = data["how_long_using_this_method"].replace(['3'], '1 year to <2 year')
data["how_long_using_this_method"] = data["how_long_using_this_method"].replace(['4'], '2 years or more')
data["how_long_using_this_method"] = data["how_long_using_this_method"].replace(['5'], 'do not remember')
data["how_long_using_this_method"] = data["how_long_using_this_method"].replace(['-1'], 'not applicable')

In [92]:
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['1'], 'Government/Municipal hospital')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['2'], 'Government dispensary')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['3'], 'UHC/UFP/UFWC')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['4'], 'CHC')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['5'], 'PHC')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['6'], 'Sub centre')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['7'], 'Governmnet Ayush hospital/clinic')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['8'], 'Government mobile clinic')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['9'], 'Camp')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['10'], 'Anganwadi/ICDS Centre')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['11'], 'ASHA/ANM')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['12'], 'Other community based worker')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['13'], 'NGO')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['14'], 'Private hospital/clinic')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['15'], 'Private Ayush hospital/clinic')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['16'], 'Pharmacy/shop')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['17'], 'Husband')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['18'], 'Friend/relative')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['19'], 'Vending machine')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['20'], 'Others')
data["method_obtain_last_time"] = data["method_obtain_last_time"].replace(['-1'], 'Not applicable')

In [93]:
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['1'], 'Wanted child now/soon')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['2'], 'Lack of knowledge')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['3'], 'Against the religion')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['4'], 'Opposed to family planning')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['5'], 'Husband opposed')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['6'], 'Other family member opposed')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['7'], 'Not linking existing methods')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['8'], 'Afraid of sterilization/operation')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['9'], 'Cannot work after sterilization/operation')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['10'], 'Worry about side effects')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['11'], 'Costs too much')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['12'], 'Health does not permit')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['13'], 'Difficult to get')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['14'], 'Inconvenient')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['15'], 'Lack of access')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['16'], 'Not living with husband presently')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['17'], 'Other')
data["reason_for_not_using_fp_method"] = data["reason_for_not_using_fp_method"].replace(['-1'], 'Not applicable')

In [94]:
data["is_method_used_in_last_5_yrs"] = data["is_method_used_in_last_5_yrs"].replace(['1'], 'Yes')
data["is_method_used_in_last_5_yrs"] = data["is_method_used_in_last_5_yrs"].replace(['2'], 'No')
data["is_method_used_in_last_5_yrs"] = data["is_method_used_in_last_5_yrs"].replace(['-1'], 'Not applicable')

In [95]:
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['1'], 'Tubectomy')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['2'], 'Vasectomy')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['3'], 'Copper-t/IUD')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['4'], 'Pills daily')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['5'], 'Pills weekly')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['6'], 'Emergency contraceptive pills')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['7'], 'Condom')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['8'], 'Other modern method')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['9'], 'Contraceptive herbs')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['10'], 'Rhythm/periodic abstinence')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['11'], 'Withdrawal')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['12'], 'Lactational Amenorrhoea Method')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['13'], 'Other traditional method')
data["method_type_used_in_last_5_yrs"] = data["method_type_used_in_last_5_yrs"].replace(['-1'], 'Not applicable')

In [96]:
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['1'], 'Wanted child')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['2'], 'Method failed')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['3'], 'Supply not available')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['4'], 'Difficult to get method')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['5'], 'Weakness')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['6'], 'Body/back ache')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['7'], 'Cramps')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['8'], 'Weight gain')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['9'], 'Dizziness')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['10'], 'Nausea')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['11'], 'Breast tenderness')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['12'], 'Irregular periods')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['13'], 'Excessive bleeding')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['14'], 'Spotting')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['14'], 'White discharge')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['16'], 'Lack of pleasure')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['17'], 'Inconvenient')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['18'], 'Other')
data["reason_for_discontinuation"] = data["reason_for_discontinuation"].replace(['-1'], 'Not applicable')

In [97]:
data["when_method_is_going_to_use"] = data["when_method_is_going_to_use"].replace(['1'], 'Within 6 months')
data["when_method_is_going_to_use"] = data["when_method_is_going_to_use"].replace(['2'], '6 months to <1 year')
data["when_method_is_going_to_use"] = data["when_method_is_going_to_use"].replace(['3'], '1 year to <2 year')
data["when_method_is_going_to_use"] = data["when_method_is_going_to_use"].replace(['4'], '2 years or after')
data["when_method_is_going_to_use"] = data["when_method_is_going_to_use"].replace(['-1'], 'Not applicable')

In [98]:
data["want_more_childern"] = data["want_more_childern"].replace(['1'], 'Yes')
data["want_more_childern"] = data["want_more_childern"].replace(['2'], 'No')
data["want_more_childern"] = data["want_more_childern"].replace(['3'], 'Not decided')
data["want_more_childern"] = data["want_more_childern"].replace(['-1'], 'Not applicable')

In [99]:
data["next_child_preference"] = data["next_child_preference"].replace(['1'], 'Boy')
data["next_child_preference"] = data["next_child_preference"].replace(['2'], 'Girl')
data["next_child_preference"] = data["next_child_preference"].replace(['3'], 'Does not matter')
data["next_child_preference"] = data["next_child_preference"].replace(['-1'], 'Not applicable')

In [100]:
data["time_for_next_child"] = data["time_for_next_child"].replace(['1'], 'Soon/Now/Less than 1 year')
data["time_for_next_child"] = data["time_for_next_child"].replace(['2'], '1 year to <2 year')
data["time_for_next_child"] = data["time_for_next_child"].replace(['3'], '2 year to <3 year')
data["time_for_next_child"] = data["time_for_next_child"].replace(['4'], '3 years or more')
data["time_for_next_child"] = data["time_for_next_child"].replace(['5'], 'Not decided')
data["time_for_next_child"] = data["time_for_next_child"].replace(['-1'], 'Not applicable')

In [101]:
data["anm_in_last_3_months"] = data["anm_in_last_3_months"].replace(['1'], 'Yes')
data["anm_in_last_3_months"] = data["anm_in_last_3_months"].replace(['2'], 'No')
data["anm_in_last_3_months"] = data["anm_in_last_3_months"].replace(['3'], 'Data not given')

In [102]:
data["aware_abt_rti"] = data["aware_abt_rti"].replace(['1'], 'Yes')
data["aware_abt_rti"] = data["aware_abt_rti"].replace(['2'], 'No')

In [103]:
data["aware_abt_hiv"] = data["aware_abt_hiv"].replace(['1'], 'Yes')
data["aware_abt_hiv"] = data["aware_abt_hiv"].replace(['2'], 'No')

In [104]:
data["aware_of_the_danger_signs"] = data["aware_of_the_danger_signs"].replace(['1'], 'Yes')
data["aware_of_the_danger_signs"] = data["aware_of_the_danger_signs"].replace(['2'], 'No')

In [105]:
data["religion"] = data["religion"].replace(['1'], 'Hindi')
data["religion"] = data["religion"].replace(['2'], 'Muslim')
data["religion"] = data["religion"].replace(['3'], 'Christian')
data["religion"] = data["religion"].replace(['4'], 'Sikh')
data["religion"] = data["religion"].replace(['5'], 'Buddhist')
data["religion"] = data["religion"].replace(['6'], 'Jain')
data["religion"] = data["religion"].replace(['7'], 'Other')
data["religion"] = data["religion"].replace(['8'], 'No religion')

In [106]:
data["social_group_code"] = data["social_group_code"].replace(['1'], 'SC')
data["social_group_code"] = data["social_group_code"].replace(['2'], 'ST')
data["social_group_code"] = data["social_group_code"].replace(['3'], 'Others')

In [107]:
data["highest_qualification"] = data["highest_qualification"].replace(['0'], 'Illiterate')
data["highest_qualification"] = data["highest_qualification"].replace(['1'], 'Literate without formal education')
data["highest_qualification"] = data["highest_qualification"].replace(['2'], 'Below primary')
data["highest_qualification"] = data["highest_qualification"].replace(['3'], 'Primary')
data["highest_qualification"] = data["highest_qualification"].replace(['4'], 'Middle')
data["highest_qualification"] = data["highest_qualification"].replace(['5'], 'Secondary/Matric (Class X)')
data["highest_qualification"] = data["highest_qualification"].replace(['6'], 'Hr.secondary/Sr.secondary/Pre-university (Class XII)')
data["highest_qualification"] = data["highest_qualification"].replace(['7'], 'Graduate/B.Tech/B.B.A/MBBS/Equivalent')
data["highest_qualification"] = data["highest_qualification"].replace(['8'], 'Post grad/M.Tech/M.B.A/MD/Equivalent')
data["highest_qualification"] = data["highest_qualification"].replace(['9'], 'Non-technical/Technical diploma-not equivalent to a degree')

In [108]:
data["occupation_status"] = data["occupation_status"].replace(['1'], 'Cultivator')
data["occupation_status"] = data["occupation_status"].replace(['2'], 'Agricultural wage labourer')
data["occupation_status"] = data["occupation_status"].replace(['3'], 'Non-agricultural wage labourer')
data["occupation_status"] = data["occupation_status"].replace(['4'], 'Self-employed own account workers')
data["occupation_status"] = data["occupation_status"].replace(['5'], 'Self-employed employers')
data["occupation_status"] = data["occupation_status"].replace(['6'], 'Self-employed unpaid family labourer')
data["occupation_status"] = data["occupation_status"].replace(['7'], 'Regular salaried/wage employees')
data["occupation_status"] = data["occupation_status"].replace(['8'], 'Did not work but was seeking and/or available for work')
data["occupation_status"] = data["occupation_status"].replace(['9'], 'Attended educational Institution')
data["occupation_status"] = data["occupation_status"].replace(['10'], 'Attending routine domestic chores, etc.')
data["occupation_status"] = data["occupation_status"].replace(['11'], 'Beggar')
data["occupation_status"] = data["occupation_status"].replace(['12'], 'Prostitutes/Sex Workers')
data["occupation_status"] = data["occupation_status"].replace(['13'], 'Rentiers, Pensioners, Other remittance recipients.')
data["occupation_status"] = data["occupation_status"].replace(['14'], 'Not able to work due to disability')
data["occupation_status"] = data["occupation_status"].replace(['15'], 'Too old to work')
data["occupation_status"] = data["occupation_status"].replace(['16'], 'Others')

In [109]:
data["disability_status"] = data["disability_status"].replace(['0'], 'None')
data["disability_status"] = data["disability_status"].replace(['1'], 'Mental')
data["disability_status"] = data["disability_status"].replace(['2'], 'Visual')
data["disability_status"] = data["disability_status"].replace(['3'], 'Hearing')
data["disability_status"] = data["disability_status"].replace(['4'], 'Speech')
data["disability_status"] = data["disability_status"].replace(['5'], 'Locomotor')
data["disability_status"] = data["disability_status"].replace(['6'], 'Multiple')
data["disability_status"] = data["disability_status"].replace(['7'], 'Other')

In [110]:
data["injury_treatment_type"] = data["injury_treatment_type"].replace(['0'], 'No injury')
data["injury_treatment_type"] = data["injury_treatment_type"].replace(['1'], 'Treated  in intensive care unit for any time')
data["injury_treatment_type"] = data["injury_treatment_type"].replace(['2'], 'Treated  as in-patient – with stay > 2 weeks')
data["injury_treatment_type"] = data["injury_treatment_type"].replace(['3'], 'Treated  as in-patient – with stay 1-2 weeks')
data["injury_treatment_type"] = data["injury_treatment_type"].replace(['4'], 'Treated  as in-patient – with stay < 1 week')
data["injury_treatment_type"] = data["injury_treatment_type"].replace(['5'], 'Treated as out-patient')
data["injury_treatment_type"] = data["injury_treatment_type"].replace(['6'], 'Treated by Traditional Healers')
data["injury_treatment_type"] = data["injury_treatment_type"].replace(['7'], 'Treated at home')

In [111]:
data["illness_type"] = data["illness_type"].replace(['0'], 'No illness')
data["illness_type"] = data["illness_type"].replace(['1'], 'Diarrhoea')
data["illness_type"] = data["illness_type"].replace(['2'], 'Dysentery')
data["illness_type"] = data["illness_type"].replace(['3'], 'Acute respiratory infection')
data["illness_type"] = data["illness_type"].replace(['4'], 'Jaundice with fever')
data["illness_type"] = data["illness_type"].replace(['5'], 'Fever with chill/rigors (Malaria etc)')
data["illness_type"] = data["illness_type"].replace(['6'], 'Fever of short duration with rashes')
data["illness_type"] = data["illness_type"].replace(['7'], 'Other types of fever')
data["illness_type"] = data["illness_type"].replace(['8'], 'Reproductive Tract Infection (RTI)')
data["illness_type"] = data["illness_type"].replace(['9'], 'Others')

In [112]:
data["diagnosed_for"] = data["diagnosed_for"].replace(['1'], 'Diabetes')
data["diagnosed_for"] = data["diagnosed_for"].replace(['2'], 'Hypertension')
data["diagnosed_for"] = data["diagnosed_for"].replace(['3'], 'Chronic heart disease/failure')
data["diagnosed_for"] = data["diagnosed_for"].replace(['4'], 'Myocardial infarction/heart attack')
data["diagnosed_for"] = data["diagnosed_for"].replace(['5'], 'Stroke/Cerebrovascular accident')
data["diagnosed_for"] = data["diagnosed_for"].replace(['6'], 'Epilepsy')
data["diagnosed_for"] = data["diagnosed_for"].replace(['7'], 'Asthma/chronic respiratory failure')
data["diagnosed_for"] = data["diagnosed_for"].replace(['8'], 'Goitre/ Thyroid disorder')
data["diagnosed_for"] = data["diagnosed_for"].replace(['9'], 'Tuberculosis')
data["diagnosed_for"] = data["diagnosed_for"].replace(['10'], 'Leprosy')
data["diagnosed_for"] = data["diagnosed_for"].replace(['11'], 'Cancer-Respiratory system')
data["diagnosed_for"] = data["diagnosed_for"].replace(['12'], 'Cancer-Gastro-intestinal system')
data["diagnosed_for"] = data["diagnosed_for"].replace(['13'], 'Cancer-Genitourinary system')
data["diagnosed_for"] = data["diagnosed_for"].replace(['14'], 'Cancer-Breast')
data["diagnosed_for"] = data["diagnosed_for"].replace(['15'], 'Renal stone')
data["diagnosed_for"] = data["diagnosed_for"].replace(['16'], 'Chronic renal failure')
data["diagnosed_for"] = data["diagnosed_for"].replace(['17'], 'Gall stone /cholecystitis')
data["diagnosed_for"] = data["diagnosed_for"].replace(['18'], 'Chronic  liver failure')
data["diagnosed_for"] = data["diagnosed_for"].replace(['19'], 'Rheumatoid arthritis /  osteoarthritis')
data["diagnosed_for"] = data["diagnosed_for"].replace(['20'], 'Chronic skin  diseases – psoriasis')
data["diagnosed_for"] = data["diagnosed_for"].replace(['21'], 'Others (Hernia, hydrocele , peptic ulcer etc)')
data["diagnosed_for"] = data["diagnosed_for"].replace(['99'], 'Others')
data["diagnosed_for"] = data["diagnosed_for"].replace(['0'], 'Not diagnosed')

In [113]:
data["chew"] = data["chew"].replace(['0'], 'Not known')
data["chew"] = data["chew"].replace(['1'], 'Pan with tobacco')
data["chew"] = data["chew"].replace(['2'], 'Pan without tobacco')
data["chew"] = data["chew"].replace(['3'], 'Gutka/pan masala with tobacco')
data["chew"] = data["chew"].replace(['4'], 'Gutka/pan masala without tobacco')
data["chew"] = data["chew"].replace(['5'], 'Tobacco only')
data["chew"] = data["chew"].replace(['6'], 'Ex-chewer')
data["chew"] = data["chew"].replace(['7'], 'Never chewed')
data["chew"] = data["chew"].replace(['8'], 'Not known')

In [114]:
data["smoke"] = data["smoke"].replace(['1'], 'Usual smoker')
data["smoke"] = data["smoke"].replace(['2'], 'Occasional smoker')
data["smoke"] = data["smoke"].replace(['3'], 'Ex-smoker')
data["smoke"] = data["smoke"].replace(['4'], 'Never smoked')
data["smoke"] = data["smoke"].replace(['0'], 'Not known')
data["smoke"] = data["smoke"].replace(['5'], 'Not known')

In [115]:
data["alcohol"] = data["alcohol"].replace(['0'], 'Not known')
data["alcohol"] = data["alcohol"].replace(['1'], 'Usual drinker')
data["alcohol"] = data["alcohol"].replace(['2'], 'Occasional drinker')
data["alcohol"] = data["alcohol"].replace(['3'], 'Ex-drinker')
data["alcohol"] = data["alcohol"].replace(['4'], 'Never drank')
data["alcohol"] = data["alcohol"].replace(['5'], 'Not known')

In [116]:
data["house_status"] = data["house_status"].replace(['1'], 'Residential/partly residential')
data["house_status"] = data["house_status"].replace(['2'], 'Non-residential')
data["house_status"] = data["house_status"].replace(['3'], 'Vacant')
data["house_status"] = data["house_status"].replace(['4'], 'New house')

In [117]:
data["house_structure"] = data["house_structure"].replace(['1'], 'Pucca')
data["house_structure"] = data["house_structure"].replace(['2'], 'Semi pucca')
data["house_structure"] = data["house_structure"].replace(['3'], 'Kuccha')
data["house_structure"] = data["house_structure"].replace(['4'], 'Others')

In [118]:
data["owner_status"] = data["owner_status"].replace(['1'], 'Owned')
data["owner_status"] = data["owner_status"].replace(['2'], 'Rented')
data["owner_status"] = data["owner_status"].replace(['3'], 'Others')

In [119]:
data["drinking_water_source"] = data["drinking_water_source"].replace(['1'], 'Piped water into dwelling/yard/plot')
data["drinking_water_source"] = data["drinking_water_source"].replace(['2'], 'Public tap/standpipe')
data["drinking_water_source"] = data["drinking_water_source"].replace(['3'], 'Hand pump')
data["drinking_water_source"] = data["drinking_water_source"].replace(['4'], 'Tube well or Borehole')
data["drinking_water_source"] = data["drinking_water_source"].replace(['5'], 'Protected dug well')
data["drinking_water_source"] = data["drinking_water_source"].replace(['6'], 'Unprotected dug well')
data["drinking_water_source"] = data["drinking_water_source"].replace(['7'], 'Tanker /truck/Cart with Surface watersmall tank')
data["drinking_water_source"] = data["drinking_water_source"].replace(['8'], 'Surface water')
data["drinking_water_source"] = data["drinking_water_source"].replace(['9'], 'Other')

In [120]:
data["is_water_filter"] = data["is_water_filter"].replace(['1'], 'Yes')
data["is_water_filter"] = data["is_water_filter"].replace(['2'], 'No')

In [121]:
data["toilet_used"] = data["toilet_used"].replace(['1'], 'To piped sewer system')
data["toilet_used"] = data["toilet_used"].replace(['2'], 'To septic tank')
data["toilet_used"] = data["toilet_used"].replace(['3'], 'To pit latrine')
data["toilet_used"] = data["toilet_used"].replace(['4'], 'To somewhere else')
data["toilet_used"] = data["toilet_used"].replace(['5'], 'Ventilated Improved Pit (VIP)')
data["toilet_used"] = data["toilet_used"].replace(['6'], 'Pit latrine with slab')
data["toilet_used"] = data["toilet_used"].replace(['7'], 'Open pit /Pit latrine without slab')
data["toilet_used"] = data["toilet_used"].replace(['8'], 'service latrine')
data["toilet_used"] = data["toilet_used"].replace(['9'], 'community toilet')
data["toilet_used"] = data["toilet_used"].replace(['0'], 'open defecation(field, brush,jungle etc.)')

In [122]:
data["household_have_electricity"] = data["household_have_electricity"].replace(['1'], 'Yes')
data["household_have_electricity"] = data["household_have_electricity"].replace(['2'], 'No')

In [123]:
data["lighting_source"] = data["lighting_source"].replace(['1'], 'Electricity')
data["lighting_source"] = data["lighting_source"].replace(['2'], 'Kerosene')
data["lighting_source"] = data["lighting_source"].replace(['3'], 'Solar')
data["lighting_source"] = data["lighting_source"].replace(['4'], 'Other oils')
data["lighting_source"] = data["lighting_source"].replace(['5'], 'Any other')
data["lighting_source"] = data["lighting_source"].replace(['6'], 'None')

In [124]:
data["cooking_fuel"] = data["cooking_fuel"].replace(['1'], 'Firewood')
data["cooking_fuel"] = data["cooking_fuel"].replace(['2'], 'Crop residue')
data["cooking_fuel"] = data["cooking_fuel"].replace(['3'], 'Cow dung cake')
data["cooking_fuel"] = data["cooking_fuel"].replace(['4'], 'Coal/lignite/Charcoal')
data["cooking_fuel"] = data["cooking_fuel"].replace(['5'], 'Kerosene')
data["cooking_fuel"] = data["cooking_fuel"].replace(['6'], 'LPG/PNG')
data["cooking_fuel"] = data["cooking_fuel"].replace(['7'], 'Electricity')
data["cooking_fuel"] = data["cooking_fuel"].replace(['8'], 'Biogas')
data["cooking_fuel"] = data["cooking_fuel"].replace(['9'], 'Any other')
data["cooking_fuel"] = data["cooking_fuel"].replace(['0'], 'None')

In [125]:
data["kitchen_availability"] = data["kitchen_availability"].replace(['1'], 'Inside house: have kitchen')
data["kitchen_availability"] = data["kitchen_availability"].replace(['2'], 'Inside house: no kitchen')
data["kitchen_availability"] = data["kitchen_availability"].replace(['3'], 'Outside house: have kitchen')
data["kitchen_availability"] = data["kitchen_availability"].replace(['4'], 'Outside house: No kitchen')
data["kitchen_availability"] = data["kitchen_availability"].replace(['5'], 'None')

In [126]:
data["is_radio"] = data["is_radio"].replace(['1'], 'Yes')
data["is_radio"] = data["is_radio"].replace(['2'], 'No')

In [127]:
data["is_television"] = data["is_television"].replace(['1'], 'Yes')
data["is_television"] = data["is_television"].replace(['2'], 'No')

In [128]:
data["is_computer"] = data["is_computer"].replace(['1'], 'With internet')
data["is_computer"] = data["is_computer"].replace(['2'], 'Without internet')
data["is_computer"] = data["is_computer"].replace(['3'], 'No')

In [129]:
data["is_telephone"] = data["is_telephone"].replace(['1'], 'Telephone only')
data["is_telephone"] = data["is_telephone"].replace(['2'], 'Mobile phone only')
data["is_telephone"] = data["is_telephone"].replace(['3'], 'Both')
data["is_telephone"] = data["is_telephone"].replace(['4'], 'No')

In [130]:
data["is_washing_machine"] = data["is_washing_machine"].replace(['1'], 'Yes')
data["is_washing_machine"] = data["is_washing_machine"].replace(['2'], 'No')

In [131]:
data["is_refrigerator"] = data["is_refrigerator"].replace(['1'], 'Yes')
data["is_refrigerator"] = data["is_refrigerator"].replace(['2'], 'No')

In [132]:
data["is_sewing_machine"] = data["is_sewing_machine"].replace(['1'], 'Yes')
data["is_sewing_machine"] = data["is_sewing_machine"].replace(['2'], 'No')

In [133]:
data["is_bicycle"] = data["is_bicycle"].replace(['1'], 'Yes')
data["is_bicycle"] = data["is_bicycle"].replace(['2'], 'No')

In [134]:
data["is_scooter"] = data["is_scooter"].replace(['1'], 'Yes')
data["is_scooter"] = data["is_scooter"].replace(['2'], 'No')

In [135]:
data["is_car"] = data["is_car"].replace(['1'], 'Yes')
data["is_car"] = data["is_car"].replace(['2'], 'No')

In [136]:
data["is_tractor"] = data["is_tractor"].replace(['1'], 'Yes')
data["is_tractor"] = data["is_tractor"].replace(['2'], 'No')

In [137]:
data["is_water_pump"] = data["is_water_pump"].replace(['1'], 'Yes')
data["is_water_pump"] = data["is_water_pump"].replace(['2'], 'No')

In [138]:
data["cart"] = data["cart"].replace(['1'], 'YesDriven by Animal')
data["cart"] = data["cart"].replace(['2'], 'Driven by Machine')
data["cart"] = data["cart"].replace(['3'], 'Other')
data["cart"] = data["cart"].replace(['4'], 'Does not have')

In [139]:
data["land_possessed"] = data["land_possessed"].replace(['1'], 'Less than 0.02')
data["land_possessed"] = data["land_possessed"].replace(['2'], '0.02 to less than 1.00')
data["land_possessed"] = data["land_possessed"].replace(['3'], '1.00 to less than 4.00')
data["land_possessed"] = data["land_possessed"].replace(['4'], '4.00 to less than 10.00')
data["land_possessed"] = data["land_possessed"].replace(['5'], '10.00 or more')
data["land_possessed"] = data["land_possessed"].replace(['6'], 'None')

In [140]:
data["ever_conceived"] = data["ever_conceived"].replace(['1'], 'Yes')
data["ever_conceived"] = data["ever_conceived"].replace(['2'], 'No')

In [141]:
data["is_injectable_contraceptive"] = data["is_injectable_contraceptive"].replace(['1'], 'Yes')
data["is_injectable_contraceptive"] = data["is_injectable_contraceptive"].replace(['2'], 'No')
data["is_injectable_contraceptive"] = data["is_injectable_contraceptive"].replace(['-1'], 'Not applicable')

In [142]:
data["health_prob_afters_fp_use"] = data["health_prob_afters_fp_use"].replace(['1'], 'Yes')
data["health_prob_afters_fp_use"] = data["health_prob_afters_fp_use"].replace(['2'], 'No')
data["health_prob_afters_fp_use"] = data["health_prob_afters_fp_use"].replace(['-1'], 'Not applicable')

In [143]:
data["counselled_for_menstrual_hyg"] = data["counselled_for_menstrual_hyg"].replace(['1'], 'Yes')
data["counselled_for_menstrual_hyg"] = data["counselled_for_menstrual_hyg"].replace(['2'], 'No')

In [144]:
data["aware_abt_haf"] = data["aware_abt_haf"].replace(['1'], 'Yes')
data["aware_abt_haf"] = data["aware_abt_haf"].replace(['2'], 'No')

In [145]:
data["aware_abt_ort_ors"] = data["aware_abt_ort_ors"].replace(['1'], 'Yes')
data["aware_abt_ort_ors"] = data["aware_abt_ort_ors"].replace(['2'], 'No')

In [146]:
data["aware_abt_ort_ors_zinc"] = data["aware_abt_ort_ors_zinc"].replace(['1'], 'Yes')
data["aware_abt_ort_ors_zinc"] = data["aware_abt_ort_ors_zinc"].replace(['2'], 'No')

In [147]:
data["aware_abt_danger_signs_new_born"] = data["aware_abt_danger_signs_new_born"].replace(['1'], 'Yes')
data["aware_abt_danger_signs_new_born"] = data["aware_abt_danger_signs_new_born"].replace(['2'], 'No')

In [148]:
data["iscoveredbyhealthscheme"] = data["iscoveredbyhealthscheme"].replace(['1'], 'Yes')
data["iscoveredbyhealthscheme"] = data["iscoveredbyhealthscheme"].replace(['2'], 'No')
data["iscoveredbyhealthscheme"] = data["iscoveredbyhealthscheme"].replace(['3'], 'Do not know')

In [149]:
data["intend_to_use_fp_method_in_futur"] = data["intend_to_use_fp_method_in_futur"].replace(['1'], 'Yes')
data["intend_to_use_fp_method_in_futur"] = data["intend_to_use_fp_method_in_futur"].replace(['2'], 'No')
data["intend_to_use_fp_method_in_futur"] = data["intend_to_use_fp_method_in_futur"].replace(['-1'], 'Not applicable')

In [150]:
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['1'], 'Tubectomy')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['2'], 'Vasectomy')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['3'], 'Copper-t/IUD')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['4'], 'Pills daily')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['5'], 'Pills weekly')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['6'], 'Emergency contraceptive pill')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['7'], 'Condom')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['8'], 'Other modern method')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['9'], 'Contraceptive herbs')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['10'], 'Rhythm/periodic abstinence')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['11'], 'Withdrawal')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['12'], 'Lactational amenorrhoea method')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['13'], 'Other traditional method')
data["which_method_going_to_pefer_for_"] = data["which_method_going_to_pefer_for_"].replace(['-1'], 'Not applicable')

In [151]:
data

,district,rural,stratum_code,age,marital_status,delivered_any_baby,born_alive_female,born_alive_male,born_alive_total,surviving_female,...,no_of_times_conceived,age_at_first_conception,is_injectable_contraceptive,health_prob_afters_fp_use,counselled_for_menstrual_hyg,aware_abt_haf,aware_abt_ort_ors,aware_abt_ort_ors_zinc,aware_abt_danger_signs_new_born,iscoveredbyhealthscheme
0,Hardwar,Rural,2,42,Married and Gauna performed,Yes,2,1,3,2,...,3,18,No,No,No,Yes,Yes,No,No,No
1,Hardwar,Rural,2,47,Married and Gauna performed,Yes,3,3,6,3,...,7,17,No,Not applicable,No,Yes,Yes,No,No,No
2,Hardwar,Rural,2,32,Married and Gauna performed,Yes,2,2,4,1,...,6,19,Yes,Not applicable,No,Yes,Yes,No,No,No
3,Hardwar,Rural,2,20,Married and Gauna performed,Yes,1,0,1,1,...,2,17,No,Not applicable,Yes,Yes,Yes,No,No,Yes
4,Hardwar,Rural,2,27,Married and Gauna performed,Yes,0,3,3,0,...,3,19,Yes,No,Yes,Yes,Yes,No,No,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
905972,Chamoli,Urban,0,36,Married and Gauna performed,Yes,2,4,6,2,...,6,19,Yes,Not applicable,No,Yes,Yes,Yes,Yes,No
905973,Chamoli,Urban,0,39,Married and Gauna performed,Yes,2,1,3,2,...,3,15,No,Not applicable,No,Yes,Yes,No,Yes,No
905974,Chamoli,Urban,0,41,Married and Gauna performed,Yes,1,2,3,1,...,3,22,Not applicable,Not applicable,No,No,No,No,No,No
905975,Chamoli,Urban,0,38,Married and Gauna performed,Yes,1,1,2,1,...,2,22,No,Not applicable,No,Yes,Yes,No,Yes,No
905976,Chamoli,Urban,0,43,Married and Gauna performed,Yes,1,1,2,1,...,2,19,Yes,Not applicable,No,Yes,Yes,Yes,Yes,No

In [152]:
data.to_csv('clean5_string.csv')

In [155]:
data['outcome_pregnancy'].value_counts()

2.0     757037
1.0     129909
nan      19030
21.0         1
Name: outcome_pregnancy, dtype: int64